[pytest]
filterwarnings =
    error
    ignore:`torch\.jit\.script` is deprecated\. Please switch to `torch\.compile` or `torch\.export`\.:DeprecationWarning:torch\.jit\._script
    ignore:None of the inputs have requires_grad=True\. Gradients will be None:UserWarning:torch\.utils\.checkpoint
    ignore:Using default support configuration\.:UserWarning:diffSPH\.regions
